[package]
name = "shotcaller"
version = "0.1.0"
authors = ["Sindre Sogge Heggen <sindre.heggen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.7"
geo = "0.2.6"
macroquad-tiled = "0.1"

